name: 🚀 Deploy del sitio web
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4
      - name: Instalar
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - name: Instalar Dependencias
        run: bun install
      - name: build
        run: bun run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}