name: Lintear y Formatear coidgo
on: [push]
jobs:
  lint-code:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Obtener el código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18

      - name: Cache bun dependencies
        id: cache-bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Instalar Dependencias con bun
        run: bun install

      - name: Formatear y lintear código con biome
        run: bun run lint

      - name: Hacer commit y push de los cambios
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "💄 style: aplicar lint al código"
            
